apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
        version: beta-{{gitops.version}}
        deploy: {{gitops.deploy}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always

          args: 
          - --in-memory
          - --prometheus
          - --url-prefix
          - {{gitops.config.urlprefix}}
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

      nodeSelector:
        agentpool: {{gitops.config.agentpool}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{gitops.name}}-ingress
  namespace: {{gitops.namespace}}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: traefik-internal
    # kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: default
    traefik.ingress.kubernetes.io/router.middlewares: {{gitops.config.stripprefix}}
spec:
  # ingressClassName: "traefik-internal"
  tls:
  - hosts:
      - {{gitops.config.host}}
  rules:
  - host: {{gitops.config.host}}
    http:
      paths:
      - path: {{gitops.config.urlprefix}}
        pathType: Prefix
        backend:
          service:
            name: {{gitops.name}}
            port:
              number: 8080
